# -*- coding: utf-8 -*-
"""Bandas de Bollinger.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10picsb-AwqUu525GjIvoEr-9CrYtfmFL
"""

import yfinance as yf
import pandas as pd
import numpy as np

#pegar a ação que queremos trabalhar
acao = yf.Ticker("CXSE3.SA")
data = acao.history(period='1y')
df = data[['Close']]
df

#Calcular a média movel
mm = df.rolling(window=20).mean()
mm

#Calculo do desvio padrão
dpm=df.rolling(window=20).std()
dpm

#Calculo da banda superior e inferior
sup_band = mm + 2 * dpm
inf_band = mm - 2 * dpm

#Alterar nome das colunas de banda sup e banda inf
sup_band = sup_band.rename(columns = {'Close': 'superior'})
inf_band = inf_band.rename(columns = {'Close': 'inferior'})

#unir as colunas
bandas_bollinger = df.join(sup_band).join(inf_band)
bandas_bollinger

#retirar os nulos
bandas_bollinger.dropna(inplace=True)

#calculo dos pontos de compra e venda
compra = bandas_bollinger[bandas_bollinger['Close'] <= bandas_bollinger['inferior']]
venda = bandas_bollinger[bandas_bollinger['Close'] >= bandas_bollinger['superior']]

#pip install ploty

#Plotar no gráfico

import plotly.io as pio
import plotly.graph_objects as go

pio.templates.default = "plotly_dark"

fig = go.Figure()
fig.add_trace(go.Scatter(x=inf_band.index,
                         y=inf_band['inferior'],
                         name='Banda Inferior',
                         line_color='rgba(173,204,255,0.2)'
                        ))
fig.add_trace(go.Scatter(x=sup_band.index,
                         y=sup_band['superior'],
                         name='Banda Superior',
                         fill='tonexty',
                         fillcolor='rgba(173,204,255,0.2)',
                         line_color='rgba(173,204,255,0.2)'
                        ))
fig.add_trace(go.Scatter(x=df.index,
                         y=df['Close'],
                         name='Preco Fechamento',
                         line_color='#636EFA'
                        ))
fig.add_trace(go.Scatter(x=mm.index,
                         y=mm['Close'],
                         name='Media Movel',
                         line_color='#FECB52'
                        ))
fig.add_trace(go.Scatter(x=compra.index,
                         y=compra['Close'],
                         name='compra',
                         mode='markers',
                         marker=dict(
                             color='#00CC96',
                             size=8,
                             )
                         ))
fig.add_trace(go.Scatter(x=venda.index,
                         y=venda['Close'],
                         name='venda',
                         mode='markers',
                         marker=dict(
                             color='#EF553B',
                             size=8,
                             )
                         ))
fig.show()